# Generated by Django 4.2.24 on 2025-12-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_attendance_user_cgpa_user_register_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='std_class',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
