# Generated by Django 4.2.24 on 2025-12-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_section_user_std_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='advisor_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
