# Generated by Django 4.2.24 on 2025-12-16 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_advisor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_semester',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
